version: '3.8'
services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: micros_user
      POSTGRES_PASSWORD: 1987
      POSTGRES_DB: micros_database
    ports:
      - "5432:5432"

  patients_service:
    build: ./patients_service
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://micros_user:1987@db/micros_database

  appointments_service:
    build: ./appointments_service
    ports:
      - "8001:8001"
    depends_on:
      - patients_service

volumes:
  postgres_data:
