name: CI-CD Yandex

on:
  workflow_dispatch:

jobs:
  build-and-push-to-yc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build docker image
        run: docker build ./appointments_service --file ./appointments_service/Dockerfile --tag cr.yandex/${{ secrets.YC_REGISTRY_ID }}/appointments_service:latest
      - name: Login to YC Registry
        uses: docker/login-action@v3.0.0
        with:
          registry: cr.yandex
          username: json_key
          password: ${{ secrets.YC_KEYS }}
      - name: Push tag to YC Registry
        run: docker push cr.yandex/${{ secrets.YC_REGISTRY_ID }}/appointments_service:latest
      - name: Prepare unit tests
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          pip install -r requirements.txt
      - name: |
          pytest ./appointments_service/


