name: CI/CD Pipeline for patients_service

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: micros_user
          POSTGRES_PASSWORD: 1987
          POSTGRES_DB: micros_database
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Compose
        run: |
          sudo apt update
          sudo apt install -y docker-compose
          docker-compose -f docker-compose.yml up -d

      - name: Check container statuses
        run: |
          docker-compose ps

      - name: Run tests
        run: |
          docker-compose exec patients-service pytest ./patients_service/

      - name: Shut down Docker Compose services
        run: |
          docker-compose down

      - name: Build Docker image
        run: |
          docker-compose build patients-service
          docker tag patients_service:latest ${{ secrets.DOCKER_USERNAME }}/patients-service:latest

      - name: Log in to DockerHub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to DockerHub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/patients-service:latest
