name: CI/CD Pipeline for patients_service

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: |
          docker build ./patients_service --file ./patients_service/Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/patients-service:latest
      - name: Log in to DockerHub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker image to DockerHub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/patients-service:latest
  test:
    runs-on: ubuntu-latest
    needs: build-and-push
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: micros_user
          POSTGRES_PASSWORD: 1987
          POSTGRES_DB: micros_database
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - name: Prepare e2e tests
        run: |
          docker build ./patients_service --file ./patients_service/Dockerfile --tag back-tests
          docker run -e POSTGRES_PASSWORD=password -p 5432:5432 -d postgres:12
          sleep 5
          sudo apt update
          sudo apt install -y python3-pip
          pip install -r ./patients_service/requirements.txt
          docker run -p 8000:8000 -e POSTGRES_URL=postgresql://micros_user:1987@localhost:5432/micros_database -d back-tests

      - name: Run e2e tests
        run: |
          pytest ./patients_service/